### PR TITLE
Fix false-valued user settings being ignored (#484)

### PR DESCRIPTION
**Pull request by hofheinz**
(possible solution for #484 )

### CODE REVIEW

**Comment by aidanholm** [comment]
Thanks for the PR!

Minor nit: please change the commit message to "Fix false-valued user settings being ignored (#484)"; it's a bit too long at the moment

**Comment by hofheinz** [comment]
Ah, sure.

**Comment by aidanholm** [comment]
The best way to do that is just with `git commit --amend`; you'll need to force-push after that.

**Comment by hofheinz** [comment]
Ok, thanks for the help (sorry for the hassle -- I didn't know better before).

**Comment by aidanholm** [comment]
No hassle at all -- and it's merged!

**Comment by hofheinz** [comment]
Thanks!

**Pull request merged**
