### PR TITLE
manage dom events with luakit signals.

### PR DESCRIPTION
**Pull request by serg-kozhemyakin**
allows to register several signal handlers of same type to one dom element.

### CODE REVIEW

**Review by aidanholm — CHANGES_REQUESTED** [review]
This code looks good except for the use of `element->signals`: I'd prefer that event handlers were stored in a separate event-specific signal set.

**Comment by serg-kozhemyakin** [comment]
why? will we clash with some other signals? dom element is lua object and have this signal field. if you want to use another signal set then we need to have dup or new object just for managing signal queue. don't think that we have any other signals attached to dom elements. maybe i'm wrong of course.

**Comment by aidanholm** [comment]
That signal set is for signals added with `add_signal()`, `emit_signal()`, etc. If they were shared, a signal named `"click"` would be emitted if an event handler was attached for the click event, but this shouldn't happen: signal handlers and event handlers should be totally separate.

**Comment by serg-kozhemyakin** [comment]
in general i'm agree but i wandering why dom objects should have any luakit events. frankly i don't see any reasonable scenario for such things. but ok. it's easy to extend dom element with new signals queue i guess.

**Comment by serg-kozhemyakin** [comment]
btw, guess that simpliest thing will be add 'dom::' prefix (or any other) to any signal type. for sure it will not prevents name clashing in genral but will reduce chance of such clashing.

**Comment by serg-kozhemyakin** [comment]
patch reworked

**Comment by serg-kozhemyakin** [comment]
reworked once again and this time it looks working better (at least for me). but will be better to test it a bit more just to be sure that no new segfaults introduced

**Comment by serg-kozhemyakin** [comment]
after aprox week of using this patch it looks working ok. at least on my environment i don't have random crashes caused by segfaults or something similas. so i guess you can review it again.

**Comment by c0dev0id** [comment]
I guess aidan was ok with this code - and even it has been sitting here for 6 years, I'm going to merge it now.

**Comment by c0dev0id** [comment]
I had to revert this PR, because it's causing a segfault in the unit test "async/test_memory_leaks".

... and I don't know how to reopen this PR :/

Feel free to send a new one, but please run the "run-tests" target and watch out for segfaults and failed tests.

You can run a specific target with `luajit  tests/run_test.lua async/test_memory_leaks` for example.

**Comment by serg-kozhemyakin** [comment]
ohoho, i don't looked at luakit for several years. if you're really interested in managing dom events with luakit signals -- i can try to change fix patch, but it may take some time.

**Comment by serg-kozhemyakin** [comment]
> I had to revert this PR, because it's causing a segfault in the unit test "async/test_memory_leaks".
> 
> ... and I don't know how to reopen this PR :/
> 
> Feel free to send a new one, but please run the "run-tests" target and watch out for segfaults and failed tests.
> 
> You can run a specific target with `luajit tests/run_test.lua async/test_memory_leaks` for example.

do you have any stacktrace? i tried to run them and at least they don't crash:

```
 334   │ LOAD async/test_memory_leaks /
 335   │   [    0.200628] I [lua/lib/adblock]: found 0 filter lists
 336   │   [    0.200643] I [lua/lib/adblock]: subscriptions file '/tmp/luakit_test_3SUDI2/data/luakit/adblock/subscriptions' doesn't exist
 337   │   [    0.208502] I [lua/lib/styles]: found 0 user stylesheets
 338   │   Could not determine the accessibility bus address
 339   │ RUN  async/test_memory_leaks / test_webview_from_closed_tab_is_released
 340   │   Xlib:  extension "GLX" missing on display ":0".
 341   │   Xlib:  extension "GLX" missing on display ":0".
 342   │   libEGL warning: DRI2: failed to create any config
 343   │   libEGL warning: DRI2: failed to create any config
 344   │   EGLDisplay Initialization failed: EGL_SUCCESS
 345   │   [    0.184803] W [glib]: libenchant: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory
 346   │
 347   │   [    0.185631] W [glib]: libenchant: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory
 348   │
 349   │   [    0.187347] I [core/luah]: Loading rc: tests/async/run_test.lua
 350   │ LOAD async/test_scroll /
 351   │   [    0.198118] I [lua/lib/adblock]: found 0 filter lists
 352   │   [    0.198131] I [lua/lib/adblock]: subscriptions file '/tmp/luakit_test_CETGI2/data/luakit/adblock/subscriptions' doesn't exist
 353   │   [    0.206150] I [lua/lib/styles]: found 0 user stylesheets
 354   │   Could not determine the accessibility bus address
 355   │ RUN  async/test_scroll / test_scrolling_works
```

at least i don't see any obvious sign of crash

**Comment by c0dev0id** [comment]
There's a another segfault on undoclose. Maybe these are related. When this is fixed, I'll try to work on this one here again.

Backtrace below. 

```
  Thread 1 received signal SIGSEGV, Segmentation fault.
  0x000007b0a08e2548 in luaH_object_remove_signals (L=0x10000378, oud=1, name=0x10123758 "button-double-click")
      at common/luaobject.c:184
  184       signal_array_t *sigfuncs = signal_lookup(obj->signals, name);
  (gdb) bt
  #0  0x000007b0a08e2548 in luaH_object_remove_signals (L=0x10000378, oud=1, name=0x10123758 "button-double-click")I'll keep your diff, maybe I'll figure out what's causing this... 
      at common/luaobject.c:184
  #1  0x000007b0a08e3208 in luaH_object_remove_signals_simple (L=0x10000378) at common/luaobject.c:395
  #2  0x000007b0a08e3312 in luaH_object_remove_all_signals (signals=0x7b2b0b27de0) at common/luaobject.c:416
  #3  0x000007b0a08e34a9 in luaH_object_gc (L=0x10144490) at common/luaobject.c:443
  #4  0x000007b0a08f38f9 in luaH_widget_gc (L=0x10144490) at clib/widget.c:67
  #5  0x000007b2ccc7bf06 in lj_BC_FUNCC () from /usr/local/lib/libluajit-5.1.so.1.0
  #6  0x000007b2ccc7e3ab in gc_finalize () from /usr/local/lib/libluajit-5.1.so.1.0
  #7  0x000007b2ccc7e939 in gc_onestep () from /usr/local/lib/libluajit-5.1.so.1.0
  #8  0x000007b2ccc7ef78 in lj_gc_fullgc () from /usr/local/lib/libluajit-5.1.so.1.0
  #9  0x000007b2ccc8ef2e in lua_gc () from /usr/local/lib/libluajit-5.1.so.1.0
  #10 0x000007b2cccd6fb8 in lj_cf_collectgarbage () from /usr/local/lib/libluajit-5.1.so.1.0
  #11 0x000007b2ccc7bf06 in lj_BC_FUNCC () from /usr/local/lib/libluajit-5.1.so.1.0
  #12 0x000007b2ccc7ca23 in lj_ff_coroutine_resume () from /usr/local/lib/libluajit-5.1.so.1.0
  #13 0x000007b2ccc8e980 in lua_pcall () from /usr/local/lib/libluajitI'll keep your diff, maybe I'll figure out what's causing this... -5.1.so.1.0
  #14 0x000007b0a08dc9dc in luaH_dofunction (L=0x10000378, nargs=0, nret=0) at ./common/lualib.h:110
  #15 0x000007b0a08dc93a in luaH_loadrc (confpath=0x7b32552c7e0 "tests/async/run_test.lua", run=1) at luah.c:186
  #16 0x000007b0a08dc481 in luaH_parserc (confpath=0x7b32552c7e0 "tests/async/run_test.lua", run=1) at luah.c:199
  #17 0x000007b0a08dcc0e in main (argc=2, argv=0x7ece8a3eaac8) at luakit.c:252
```

**Comment by serg-kozhemyakin** [comment]
> There's a another segfault on undoclose. Maybe these are related. When this is fixed, I'll try to work on this one here again.
> 
> Backtrace below.
> 
> ```
>   Thread 1 received signal SIGSEGV, Segmentation fault.
>   0x000007b0a08e2548 in luaH_object_remove_signals (L=0x10000378, oud=1, name=0x10123758 "button-double-click")
>       at common/luaobject.c:184
>   184       signal_array_t *sigfuncs = signal_lookup(obj->signals, name);
>   (gdb) bt
> ```

this place easy to guard of course. i guess that obj there is null for some reason. but it should't be null is theory. as i can understand it can be null only if lua stack doesn't contain object there

**Comment by c0dev0id** [comment]
You are my hero! Not sure why I didn't see this. But this fixes your PR as well as the undoclose bug I'm hunting right now \o/

Well done, Sir! Thanks!

**Comment by serg-kozhemyakin** [comment]
yw :) will be interesting to trace stack changes during this test but at least your if there should prevent similar cases.

**Comment by balejk** [comment]
Hello,

I have been looking into fixing luakit deprecation warnings a little lately and
I noticed that this change actually adds some of these (probably due to how
long it took to get merged) so I wanted to mention it before it gets officially
released. I am not suggesting a revert since it seems like a lot of work went
into this, however I think it might be wise to evaluate whether it will be
possible to provide this functionality without using the deprecated symbols so
that there are as little future backwards incompatibilities as possible. What
do you think?

**Comment by c0dev0id** [comment]
@balejk this would be good. Maybe @serg-kozhemyakin can look into it and cook a PR with newer API calls?

**Pull request merged**
