### PR TITLE
Keysym

### PR DESCRIPTION
**Pull request by karottenreibe**
this adds the `send()` method to windows to allow sending keystrings to the window, e.g:

```
w:send(":o google.de<Return>")
```

this will allow us to implement :autocmd and a .luakitrc file

### CODE REVIEW

**Comment by mason-larobina** [comment]
Merged into branch https://github.com/mason-larobina/luakit/tree/keysym

I'm still struggling to make it work with unicode characters (lua is terrible for this).

**Comment by aidanholm** [comment]
I've rebased this off a recent `develop` commit; not yet sure if it'll be merged though.

**Comment by SolarAquarion** [comment]
@aidanholm i guess rebase the branch

**Comment by aidanholm** [comment]
I'm closing this for now, to keep the set of open PRs focused. If the updated version works with Unicode, I'll merge it.

**Pull request closed without merging**
