### PR TITLE
Fix #167 - Rebased GTK3/Webkit-GTK3 support

### LINKED ISSUE #167: GTK+ 3 (webkitgtk-3) merging
Is it possible to merge these commits into mainstream? https://github.com/liaonau/luakit/commits/webkit3

Or there some reason to not do this?

### PR DESCRIPTION
**Pull request by XVilka**
Rebased already committed patches, waiting for your feedback

### CODE REVIEW

**Comment by mason-larobina** [comment]
Sorry for leaving this for a few years. Was this ever merged into luakit-crowd?

I couldn't find any references to unique-3 so I had to disable it while compiling (`USE_UNIQUE=0 make ...`).

And the second problem: the webview renders completely blank.

**Comment by XVilka** [comment]
@mason-larobina afair it was fixed indeed a long time ago in the luakit-crowd.

**Comment by XVilka** [comment]
Hm, strangely I can't find the reference to porting it for GTK+3. But I've seen it!

**Comment by JR1994** [comment]
I just recently tried to port luakit to Gtk-3 in Debian and I got similar warnings and errors due to Gtk-3 removing stuct members and requiring the use of accessor functions. Did you see this when building against Arch?

**Comment by mason-larobina** [comment]
@JR1994 I didn't see any of the above compile warnings (with the changes in this PR).

@XVilka I thought so too but after checking their config.mk file I didn't see any mentions of gtk3 / webkitgtk3 / etc.

**Comment by JR1994** [comment]
If you have this in the config.ml file I am sure you will see them

# Packages required to build luakit.
PKGS += gtk+-3.0
PKGS += gthread-2.0
PKGS += webkit2gtk-4.0
PKGS += sqlite3
PKGs += javascriptcoregtk-4.0

I am building against javascriptcoregtk-4.0 b/c it is a dependancy of webkit2gtk

rican-linux@debian-macbookpro:~$ apt-cache depends libwebkit2gtk-4.0-dev
libwebkit2gtk-4.0-dev
  Depends: libwebkit2gtk-4.0-37
  Depends: gir1.2-webkit2-4.0
  Depends: libgtk-3-dev
  Depends: libsoup2.4-dev
  Depends: libjavascriptcoregtk-4.0-dev

**Comment by JR1994** [comment]
Nevermind. I saw the commits that were added. The changes are similar to what I did to getgtk-3 to working. I should have looked at them. sorry

**Comment by JR1994** [comment]
Is there a timeframe for adding these commits?

**Comment by aidanholm** [comment]
Thank you for all the work that went into this PR; WebKit 2 and GTK3 support has been merged into luakit, however, so I'll go ahead and close this.

**Pull request closed without merging**
