### PR TITLE
Add support for webkit's run-file-chooser signal

### PR DESCRIPTION
**Pull request by laino**
Hey. I added support for webkit's run-file-chooser signal, allowing users to replace the default GTK file chooser with something different (or just keep the file chooser from being shown).
I'm hoping that someone builds a file chooser that has previews and supports vim-like shortcuts (a chrome page, maybe?).

Well, back to the code. That were some of the first lines of C I ever wrote, but I'm pretty sure that I didn't fuck it up completely.... ;) 

I'll probably built some basic integrated file-manager to test what can be done with that tomorrow...

Good night :)

### CODE REVIEW

**Comment by aidanholm** [comment]
This mostly looks good; if anyone wants to work on this, i'd be happy to merge it after a rebase.

**Comment by SolarAquarion** [comment]
@aidanholm https://patch-diff.githubusercontent.com/raw/SolarAquarion/luakit/pull/1.patch i did a rebase of it.  

But i get this
cc -c clib/filechooser.c -o clib/filechooser.o
clib/filechooser.c: In function ‘filechooser_class_setup’:
clib/filechooser.c:148:34: error: array type has incomplete element type ‘struct luaL_reg’
     static const struct luaL_reg filechooser_methods[] =
                                  ^~~~~~~~~~~~~~~~~~~
clib/filechooser.c:154:34: error: array type has incomplete element type ‘struct luaL_reg’
     static const struct luaL_reg filechooser_meta[] =
                                  ^~~~~~~~~~~~~~~~
clib/filechooser.c:154:34: warning: unused variable ‘filechooser_meta’ [-Wunused-variable]
clib/filechooser.c:148:34: warning: unused variable ‘filechooser_methods’ [-Wunused-variable]
     static const struct luaL_reg filechooser_methods[] =
                                  ^~~~~~~~~~~~~~~~~~~
make: *** [Makefile:56: clib/filechooser.o] Error 1

**Comment by aidanholm** [comment]
@SolarAquarion luaL_reg --> luaL_Reg

**Comment by aidanholm** [comment]
I'll push a rebased version separately; thanks @laino for the contribution, and @SolarAquarion for rebasing!

**Pull request closed without merging**
